language: php

php:
- 7.0
- hhvm

before_script:
  - sudo apt-get install -y libssl-dev libcurl4-openssl-dev pkg-config libssl-dev libsslcommon2-dev                                           
  - sudo apt-get install -y mongodb git                                                                                                       
  - sudo apt-get install php-mongodb                                                                                                          
  - sudo pecl install mongodb
  - composer install

script:
  - mkdir -p build/logs
  - php bin/codecept.phar run unit

