language: php

php:
- 7.0
- hhvm

before_script:
#  - sudo sh ./mongo-php-driver-installer.sh
  - phpenv config-add php-travis.ini
  - composer install

script:
  - mkdir -p build/logs
  - php bin/codecept.phar run unit

