language: php

php:
- 7.0
- hhvm

before_script:
  - pecl install -f mongo-1.2.12
  - phpenv config-add php-travis.ini
  - composer install

script:
  - mkdir -p build/logs
  - php bin/codecept.phar run unit

